name: main build/test
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - run: |
                  python -m pip install --upgrade pip
                  pip install -r test-requirements.txt
                  pip install -r requirements.txt
            - run: make test
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - run: make build
            - uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - run: make docker-push
